# The following line is needed
# when running the example site
# from a subdir of the theme

title = "YoungLiu"
theme = "not-much"
languageCode = "en-us"
baseURL = "https://example.org/"
copyright = "Sample custom notice © {year}"

[markup]
  [markup.highlight]
    style = 'dracula'
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true


[params]
theme = "dark"
palette = "catpuccin"
showThemeNotice = true
showPostsSummary = true
preserveTaxonomyNames = true

# Giscus Comment System
[params.giscus]
repository = "username/repository"
repositoryId = "repositoryId"
categoryName = "categoryName"
categoryId = "categoryId"
mapping = "pathname"
theme = "preferred_color_scheme"
language = "en"
lazyLoading = true

[params.cusdis]
  host = "https://cusdis.com"
  appId = "577a2583-65e4-4195-b410-412b79612f21"

# Navigation
[menu]
  [[menu.main]]
    identifier = "首页"
    name = "首页"
    title = "首页"
    url = "/"
    weight = 1
  
  [[menu.main]]
    identifier = "文章列表"
    name = "文章列表"
    title = "文章列表"
    url = "/posts"
    weight = 2
  
  [[menu.main]]
    identifier = "关于"
    name = "关于"
    title = "关于"
    url = "/about"
    weight = 4
  
  [[menu.main]]
    identifier = "标签"
    name = "标签"
    title = "标签"
    url = "/tags"
    weight = 3

#  [[menu.main]]
#   identifier = "github"
#   name = "github"
#   title = "GitHub"
#   url = "https://github.com/imgios/not-much"
#   weight = 5

[services]
  [services.pinyin]
    enabled = true

# 或者更彻底（推荐）
uglyURLs = false
removePathAccents = true